
const plans=[
{id:"push",name:"Push Day",emoji:"💪",summary:"Chest • Shoulders • Triceps",muscles:["Chest","Shoulders","Triceps"],exercises:[
{name:"Barbell Bench Press",sets:4,reps:8,weight:0,note:"Stop 1–2 reps before failure",rest:120},
{name:"Incline Dumbbell Press",sets:3,reps:10,weight:0,note:"Controlled lowering",rest:90},
{name:"Machine Chest Press",sets:3,reps:12,weight:0,note:"Joint-friendly option",rest:90},
{name:"Seated Dumbbell Shoulder Press",sets:3,reps:10,weight:25,note:"Keep your back supported",rest:90},
{name:"Dumbbell Lateral Raise",sets:3,reps:15,weight:12,note:"Light and controlled",rest:60},
{name:"Cable Rope Triceps Pushdown",sets:3,reps:13,weight:35,note:"Keep elbows close",rest:60},
{name:"Overhead Rope Extension",sets:3,reps:12,weight:0,note:"Do not arch your lower back",rest:60}]},
{id:"pull",name:"Pull Day",emoji:"🦾",summary:"Back • Rear delts • Biceps",muscles:["Back","Rear delts","Biceps"],exercises:[
{name:"Lat Pulldown",sets:4,reps:10,weight:0,note:"Pull elbows toward ribs",rest:90},
{name:"Seated Cable Row",sets:4,reps:10,weight:0,note:"Keep a neutral spine",rest:90},
{name:"Chest-Supported Row",sets:3,reps:12,weight:0,note:"Protect your lower back",rest:90},
{name:"Face Pull",sets:3,reps:15,weight:0,note:"Pull toward forehead",rest:60},
{name:"Rear Delt Fly Machine",sets:3,reps:15,weight:0,note:"Slow repetitions",rest:60},
{name:"Dumbbell Biceps Curl",sets:3,reps:10,weight:0,note:"Avoid swinging",rest:60},
{name:"Hammer Curl",sets:3,reps:12,weight:0,note:"Neutral grip",rest:60}]},
{id:"lower",name:"Lower Body Day",emoji:"🦵",summary:"Quads • Hamstrings • Glutes • Core",muscles:["Quads","Hamstrings","Glutes"],exercises:[
{name:"Leg Press",sets:4,reps:10,weight:0,note:"Use a comfortable knee depth",rest:120},
{name:"Seated Leg Curl",sets:3,reps:12,weight:0,note:"Pause at contraction",rest:75},
{name:"Leg Extension",sets:3,reps:12,weight:0,note:"Use a pain-free range",rest:75},
{name:"Hip Thrust Machine",sets:3,reps:10,weight:0,note:"Brace your core",rest:90},
{name:"Standing Calf Raise",sets:4,reps:15,weight:0,note:"Use full range",rest:60},
{name:"Cable Crunch",sets:3,reps:15,weight:0,note:"Move slowly",rest:60}]}];

const defaults={setupComplete:false,settings:{name:"Jorge",age:48,height:"5'9\"",goal:"fat-muscle",duration:60,gym:"Crunch Fitness - Lake Nona",jointFriendly:true},splitIndex:0,history:[],records:{},bodyHistory:[],activeWorkout:null};
let state=load(),elapsed=0,timerId=null,restSeconds=90,restTimerId=null;
const $=id=>document.getElementById(id);
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem("jorgefit-v3")||"{}")}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem("jorgefit-v3",JSON.stringify(state))}
function clone(x){return JSON.parse(JSON.stringify(x))}
function current(){return plans[state.splitIndex%plans.length]}
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".nav").forEach(n=>n.classList.remove("active"));document.querySelectorAll(`[data-view="${id}"]`).forEach(n=>n.classList.add("active"));if(id==="progressView")renderProgress()}
function startWeek(){const d=new Date(),day=d.getDay();d.setDate(d.getDate()-day);d.setHours(0,0,0,0);return d}
function fmt(d){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(d)}
function greeting(){const h=new Date().getHours();return h<12?"Good morning":h<18?"Good afternoon":"Good evening"}
function recoveryPct(m){const times=state.history.filter(h=>(h.muscles||[]).includes(m)).map(h=>new Date(h.date).getTime());if(!times.length)return 100;const hrs=(Date.now()-Math.max(...times))/36e5;return Math.min(100,Math.round(hrs/48*100))}
function renderHome(){
 const t=current();$("greeting").textContent=`${greeting()}, ${state.settings.name}`;$("todayChip").textContent=new Intl.DateTimeFormat("en-US",{weekday:"long",month:"short",day:"numeric"}).format(new Date()).toUpperCase();$("workoutName").textContent=t.name;$("workoutSummary").textContent=`${t.summary} • ${state.settings.gym}`;$("exerciseCount").textContent=t.exercises.length;$("durationCount").textContent=state.settings.duration;$("readinessCount").textContent=`${Math.round(t.muscles.reduce((s,m)=>s+recoveryPct(m),0)/t.muscles.length)}%`;
 const ws=startWeek(),we=new Date(ws);we.setDate(we.getDate()+6);$("weekRange").textContent=`${fmt(ws)}–${fmt(we)}`;const week=state.history.filter(h=>new Date(h.date)>=ws);$("weekWorkouts").textContent=week.length;$("weekVolume").textContent=`${Math.round(week.reduce((s,h)=>s+h.volume,0)).toLocaleString()} lb`;$("weekMinutes").textContent=week.reduce((s,h)=>s+h.minutes,0);
 $("splitCards").innerHTML=plans.map((p,i)=>`<button class="split-card ${i===state.splitIndex?"active":""}" data-plan="${i}"><span class="emoji">${p.emoji}</span><strong>${p.name}</strong><small>${p.exercises.length} exercises</small></button>`).join("");document.querySelectorAll("[data-plan]").forEach(b=>b.onclick=()=>{state.splitIndex=Number(b.dataset.plan);save();renderHome()});
 const muscles=["Chest","Back","Shoulders","Biceps","Triceps","Quads","Hamstrings","Glutes"];$("recoveryGrid").innerHTML=muscles.map(m=>{const p=recoveryPct(m);return `<div class="recovery"><strong>${m}</strong><span>${p}% ready</span><div class="bar"><div style="width:${p}%"></div></div></div>`}).join("");
 $("recentList").innerHTML=state.history.length?state.history.slice().reverse().slice(0,6).map(h=>`<div class="list-item"><div><strong>${h.name}</strong><p>${new Date(h.date).toLocaleDateString()} • ${h.sets} sets</p></div><div class="right"><strong>${Math.round(h.volume).toLocaleString()} lb</strong><p>${h.minutes} min</p></div></div>`).join(""):`<div class="empty">Your completed workouts will appear here.</div>`;
}
function recommended(name,base){const r=state.records[name];if(!r)return base||0;const inc=/leg|press|row|pulldown|thrust/i.test(name)?10:5;return r.ready?r.weight+inc:r.weight}
function startWorkout(){const p=clone(current());p.exercises=p.exercises.map(e=>{const w=recommended(e.name,e.weight);return {...e,done:Array(e.sets).fill(false),actualReps:Array(e.sets).fill(e.reps),actualWeights:Array(e.sets).fill(w)}});state.activeWorkout={...p,startedAt:new Date().toISOString()};save();elapsed=0;renderWorkout();show("workoutView");runTimer()}
function runTimer(){clearInterval(timerId);timerId=setInterval(()=>{elapsed++;$("timer").textContent=`${String(Math.floor(elapsed/60)).padStart(2,"0")}:${String(elapsed%60).padStart(2,"0")}`},1000)}
function startRest(sec){restSeconds=sec;updateRest();$("restDialog").showModal();clearInterval(restTimerId);restTimerId=setInterval(()=>{restSeconds--;updateRest();if(restSeconds<=0){clearInterval(restTimerId);$("restDialog").close()}},1000)}
function updateRest(){$("restTime").textContent=`${String(Math.floor(restSeconds/60)).padStart(2,"0")}:${String(restSeconds%60).padStart(2,"0")}`}
function renderWorkout(){const w=state.activeWorkout;if(!w)return;$("activeTitle").textContent=w.name;$("exerciseList").innerHTML=w.exercises.map((e,i)=>`<article class="exercise-card"><div class="exercise-top"><div><h3>${i+1}. ${e.name}</h3><p>${e.note||""}</p></div><button class="icon" data-remove="${i}">⋯</button></div><div class="sets">${e.actualReps.map((r,j)=>`<div class="set-row"><span class="set-num">${j+1}</span><input data-w="${i}-${j}" type="number" value="${e.actualWeights[j]}" placeholder="lb"><input data-r="${i}-${j}" type="number" value="${r}" placeholder="reps"><button class="complete ${e.done[j]?"done":""}" data-d="${i}-${j}">${e.done[j]?"✓":"○"}</button></div>`).join("")}</div><div class="exercise-tools"><button data-add="${i}">+ Set</button><button data-swap="${i}">Substitute</button></div></article>`).join("");
 document.querySelectorAll("[data-w]").forEach(x=>x.onchange=e=>{const[a,b]=e.target.dataset.w.split("-").map(Number);w.exercises[a].actualWeights[b]=Number(e.target.value)||0;save()});document.querySelectorAll("[data-r]").forEach(x=>x.onchange=e=>{const[a,b]=e.target.dataset.r.split("-").map(Number);w.exercises[a].actualReps[b]=Number(e.target.value)||0;save()});
 document.querySelectorAll("[data-d]").forEach(x=>x.onclick=e=>{const[a,b]=e.currentTarget.dataset.d.split("-").map(Number),ex=w.exercises[a];ex.done[b]=!ex.done[b];save();renderWorkout();if(ex.done[b])startRest(ex.rest||90)});
 document.querySelectorAll("[data-add]").forEach(x=>x.onclick=e=>{const a=Number(e.target.dataset.add),ex=w.exercises[a];ex.done.push(false);ex.actualReps.push(ex.reps);ex.actualWeights.push(ex.actualWeights.at(-1)||0);save();renderWorkout()});
 document.querySelectorAll("[data-swap]").forEach(x=>x.onclick=e=>{const a=Number(e.target.dataset.swap),v=prompt("Replacement exercise:",w.exercises[a].name);if(v?.trim()){w.exercises[a].name=v.trim();save();renderWorkout()}});
 document.querySelectorAll("[data-remove]").forEach(x=>x.onclick=e=>{const a=Number(e.currentTarget.dataset.remove);if(confirm(`Remove ${w.exercises[a].name}?`)){w.exercises.splice(a,1);save();renderWorkout()}});
 const all=w.exercises.flatMap(e=>e.done),done=all.filter(Boolean).length;$("progressBar").style.width=`${all.length?done/all.length*100:0}%`;
}
function finishWorkout(){const w=state.activeWorkout;if(!w)return;const sets=[];w.exercises.forEach(e=>e.done.forEach((d,i)=>{if(d)sets.push({name:e.name,weight:Number(e.actualWeights[i])||0,reps:Number(e.actualReps[i])||0,target:e.reps})}));if(!sets.length&&!confirm("No completed sets are marked. Finish anyway?"))return;const volume=sets.reduce((s,x)=>s+x.weight*x.reps,0),minutes=Math.max(1,Math.round(elapsed/60));w.exercises.forEach(e=>{const xs=sets.filter(x=>x.name===e.name);if(!xs.length)return;const max=Math.max(...xs.map(x=>x.weight)),top=xs.filter(x=>x.weight===max),ready=top.every(x=>x.reps>=e.reps),old=state.records[e.name];if(!old||max>=old.weight)state.records[e.name]={weight:max,reps:Math.max(...top.map(x=>x.reps)),ready,date:new Date().toISOString()}});state.history.push({date:new Date().toISOString(),name:w.name,muscles:w.muscles,sets:sets.length,volume,minutes});state.splitIndex=(state.splitIndex+1)%plans.length;state.activeWorkout=null;save();clearInterval(timerId);alert(`Workout saved. Volume: ${Math.round(volume).toLocaleString()} lb`);renderHome();show("homeView")}
function renderProgress(){const r=Object.entries(state.records).sort((a,b)=>new Date(b[1].date)-new Date(a[1].date));$("recordsList").innerHTML=r.length?r.map(([n,x])=>`<div class="list-item"><div><strong>${n}</strong><p>${new Date(x.date).toLocaleDateString()}</p></div><div class="right"><strong>${x.weight} lb × ${x.reps}</strong><p>${x.ready?"Increase next time":"Repeat next time"}</p></div></div>`).join(""):`<div class="empty">Complete workouts to build records.</div>`;$("bodyList").innerHTML=state.bodyHistory.length?state.bodyHistory.slice().reverse().slice(0,8).map(x=>`<div class="list-item"><div><strong>${new Date(x.date).toLocaleDateString()}</strong></div><div class="right"><strong>${x.weight||"—"} lb</strong><p>${x.bodyFat||"—"}% body fat</p></div></div>`).join(""):`<div class="empty">No measurements saved yet.</div>`}
$("startBtn").onclick=startWorkout;$("quickStartBtn").onclick=()=>state.activeWorkout?(renderWorkout(),show("workoutView"),runTimer()):startWorkout();$("backBtn").onclick=()=>show("homeView");$("finishBtn").onclick=finishWorkout;$("rotateBtn").onclick=()=>{state.splitIndex=(state.splitIndex+1)%plans.length;save();renderHome()};
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>show(b.dataset.view));$("clearBtn").onclick=()=>{if(confirm("Clear workout history and records?")){state.history=[];state.records={};save();renderHome()}};
$("settingsBtn").onclick=()=>{$("nameSetting").value=state.settings.name;$("durationSetting").value=state.settings.duration;$("gymSetting").value=state.settings.gym;$("jointSetting").checked=state.settings.jointFriendly;$("settingsDialog").showModal()};$("saveSettingsBtn").onclick=e=>{e.preventDefault();state.settings.name=$("nameSetting").value.trim()||"Jorge";state.settings.duration=Number($("durationSetting").value);state.settings.gym=$("gymSetting").value.trim()||"Crunch Fitness";state.settings.jointFriendly=$("jointSetting").checked;save();$("settingsDialog").close();renderHome()};
$("saveSetupBtn").onclick=e=>{e.preventDefault();state.settings={name:$("setupName").value.trim()||"Jorge",age:Number($("setupAge").value)||48,height:$("setupHeight").value.trim()||"5'9\"",goal:$("setupGoal").value,duration:Number($("setupDuration").value),gym:$("setupGym").value.trim()||"Crunch Fitness",jointFriendly:$("setupJoint").checked};state.setupComplete=true;save();$("setupDialog").close();renderHome()};
$("addExerciseBtn").onclick=()=>$("addExerciseDialog").showModal();$("confirmAddBtn").onclick=e=>{e.preventDefault();const n=$("newName").value.trim();if(!n)return;const s=Number($("newSets").value)||3,r=Number($("newReps").value)||10;state.activeWorkout.exercises.push({name:n,sets:s,reps:r,weight:0,note:"Custom exercise",rest:60,done:Array(s).fill(false),actualReps:Array(s).fill(r),actualWeights:Array(s).fill(0)});save();$("addExerciseDialog").close();$("newName").value="";renderWorkout()};
$("restMinus").onclick=()=>{restSeconds=Math.max(0,restSeconds-15);updateRest()};$("restPlus").onclick=()=>{restSeconds+=15;updateRest()};$("skipRest").onclick=()=>{clearInterval(restTimerId);$("restDialog").close()};
$("saveBodyBtn").onclick=()=>{const weight=Number($("weightInput").value)||null,bodyFat=Number($("fatInput").value)||null;if(!weight&&!bodyFat)return alert("Enter weight or body fat.");state.bodyHistory.push({date:new Date().toISOString(),weight,bodyFat});save();$("weightInput").value="";$("fatInput").value="";renderProgress()};
$("exportBtn").onclick=()=>{const b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`jorgefit-v3-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u)};
$("importInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{state={...defaults,...JSON.parse(reader.result)};save();renderHome();renderProgress();alert("Backup imported.")}catch{alert("Invalid backup file.")}};reader.readAsText(f)};
renderHome();if(!state.setupComplete)setTimeout(()=>$("setupDialog").showModal(),200);if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>{}));
